### ISSUE TITLE
libpq: failed (no connection to the server)

### ISSUE THREAD

**Issue by creichert** [lpsmith/postgresql-simple#200]
I have two projects which use AWS RDS. One uses postgresql-simple via persistent, another uses postgresql-simple plain.

A few weeks ago I started receiving this error frequently from my code on both projects:

    libpq: failed (no connection to the server)

It also comes in another variant:

    libpq: failed (ERROR: client sent partial pkt in startup phase )

The postgresql server logs do seem to spit out a corresponding error:

    could not receive data from client: Connection reset by peer

I'm at a loss on where to begin here. It's happening between both projects

I should mention that, I just recently upgraded one of the projects stackage snapshot from `lts-3.9` to `nightly-2016-08-25`. That would mean I upgraded from `postgres-simple-0.4.10.0` to `postgresql-simple-0.5.2.1`.

I didn't change any database code before the upgrade and after the upgrade I started receiving these errors.

I'm not necessarily "blaming" postgresql-simple but I am looking for suggestions and ideas on how to identify and fix this problem.

**Comment by creichert** [comment]
Update: I'm trying some different versions of `postgresql-simple` to see if I can find a version which works for me. Would appreciate any tips!

In my `stack.yaml`:

```
  - location:
      git: git@github.com:lpsmith/postgresql-simple
      #commit: a8f6a901a38df0f65906889bc7f20bf59ecdd73b
      commit: 22074e507cf45f24111a3067a706ec84905023c6
```
